[aws]
style = "bold #FFCA80"

[character]
error_symbol = "[❯](bold #FF9580)"
success_symbol = "[❯](bold #8AFF80)"

[cmd_duration]
style = "bold #FFFF80"

[directory]
style = "bold #8AFF80"

[git_branch]
style = "bold #FF80BF"

[git_status]
style = "bold #FF9580"

[hostname]
style = "bold #9580FF"

[username]
format = "[$user]($style) on "
style_user = "bold #80FFEA"
